### ISSUE TITLE
Travis failing because no database.yml exists

### ISSUE THREAD

**Issue by javierg** [rubytij/usergroup#33]

**Comment by javierg** [comment]
@EnriqueVidal wassup with this?

**Comment by EnriqueVidal** [comment]
That's not why it's failing, it's failing because pygments it's not installed please merge master into your branch first.

**Comment by javierg** [comment]
it is merge with master, it always have been, I said that becase that was the error shown in travios... anyways will close this.

**Comment by EnriqueVidal** [comment]
@javierg don't just close it, the reason you kept breaking the build is because your `.travis.yml` is not up to date, the error you see on the screen is not the absence of `config/database.yml` but because `pygments` is not installed in the CI, nor is `python-pip` the newer `.travis.yml` deals with this, please make sure to merge with master before pushing to github (regardless what the branch is), because travis will build your commit.

**Comment by javierg** [comment]
actually is up to date, maybe it wasn't in some commit, but I definitely merge it to master before the last commit, must be something else.
